services:
  app:
    image: bug-track:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - 5051:80
      - 5053:5173
  # db:
  #   image: mysql:8.0
  #   # command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #       MYSQL_DATABASE: bug-track
  #       MYSQL_USER: bug-track
  #       MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #   volumes:
  #       - ./dbdata:/var/lib/mysql
  #   ports: 
  #       - "5042:3306"